version: '3.8'

services:
  final_project-mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - ./final_project-api-db:/var/lib/mysql

  final_project-redis:
    image: redis:7.2.3
    restart: unless-stopped
    command: redis-server --requirepass '${REDIS_PASSWORD}'
    ports:
      - '${REDIS_PORT}:6379'

  final_project-file-s3:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "8000:9000"
      - "8001:9001"
    volumes:
      - ./final_project-file-api-s3-data:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password

volumes:
  final_project-api-db:
  final_project-file-api-s3: