version: '3.8'

services:
  app:
    build:
      context: .  # Шлях до директорії, де знаходиться ваш Dockerfile
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
#      - /app/dist
    restart: on-failure
    depends_on:
      - final_project-mysql
      - final_project-redis
      - final_project-file-s3
    command: >
      sh -c "node dist/main.js"
    networks:
      - default

  final_project-mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    tmpfs:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "owu.linkpc.net"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - default

  final_project-redis:
    image: redis:7.2.3
    restart: unless-stopped
    hostname: final_project-redis
    command: redis-server --requirepass '${REDIS_PASSWORD}'
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - default

  final_project-file-s3:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    volumes:
      - ./final_poroject-file-api-s3-data:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
        - default

volumes:
  mysql_data:
    driver: local

networks:
  default:
    driver: bridge

#version: '3.8'
#
#services:
#  final_project-mysql:
#    image: mysql:8.0
#    restart: unless-stopped
#    environment:
#      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
#      MYSQL_USER: '${MYSQL_USER}'
#      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
#      MYSQL_DATABASE: '${MYSQL_DB}'
#    ports:
#      - '${MYSQL_PORT}:3306'
#    volumes:
#      - ./final_project-api-db:/var/lib/mysql
#
#  final_project-redis:
#    image: redis:7.2.3
#    restart: unless-stopped
#    command: redis-server --requirepass '${REDIS_PASSWORD}'
#    ports:
#      - '${REDIS_PORT}:6379'
#
#  final_project-file-s3:
#    image: quay.io/minio/minio:latest
#    restart: unless-stopped
#    command: server /data --console-address ":9001"
#    ports:
#      - "8000:9000"
#      - "8001:9001"
#    volumes:
#      - ./final_project-file-api-s3-data:/data
#    environment:
#      MINIO_ROOT_USER: user
#      MINIO_ROOT_PASSWORD: password
#
#volumes:
#  final_project-api-db:
#  final_project-file-api-s3: