export enum SortFieldEnum {
  ID = 'id',
  NAME = 'name',
  SURNAME = 'surname',
  EMAIL = 'email',
  PHONE = 'phone',
  AGE = 'age',
  COURSE = 'course',
  COURSE_FORMAT = 'course_format',
  COURSE_TYPE = 'course_type',
  STATUS = 'status',
  SUM = 'sum',
  ALREADY_PAID = 'alreadyPaid',
  CREATED_AT = 'created_at',
  GROUP_ID = 'group_id',
  GROUP_NAME = 'group_name',
  MANAGER = 'manager',
}
