import { SortFieldEnum } from '../../module/enums/sortFieldEnum';
import { SortASCOrDESCEnum } from '../../module/enums/sortASCOrDESCEnum';
import { OrderSliceInterface } from '../interface/orderSlice_interface';

export const initialStateOrder: OrderSliceInterface = {
  dataExel: '',
  data: {
    orders: [],
    total: 0,
  },
  dto: {
    name: null,
    surname: null,
    email: null,
    phone: null,
    age: null,
    course: null,
    course_format: null,
    course_type: null,
    status: null,
    sum: null,
    alreadyPaid: null,
    manager: null,
    group_id:  null,
    group_name: null,
    limit: 25,
    page: 1,
    sortField: SortFieldEnum.CREATED_AT,
    sortASCOrDESC: SortASCOrDESCEnum.DESC,
    my: false,
  },
  findOneOrder: {
    id: null,
    name: null,
    surname: null,
    email: null,
    phone: null,
    age: null,
    course:null,
    course_format: null,
    course_type: null,
    status: null,
    sum: null,
    alreadyPaid: null,
    created_at: null,
    updated_at: null,
    manager: null,
    authManager: null,
    group_id: null,
    group_name: null,
    messages: null,
    utm: null,
    msg: null,
  },
  loadingExel: false,
  exportSuccess: null,
  messagesOrderId: [],
  createMessage: {
    id: 0,
    messages: '',
    orderId: 0,
    manager: null,
    created_at: null,
  },
  createMessageError: null,
  isEditOrder: false,
  editOrder:{
    id: null,
    name: null,
    surname: null,
    email: null,
    phone: null,
    age: null,
    course: null,
    course_format: null,
    course_type: null,
    status: null,
    sum: null,
    alreadyPaid: null,
    created_at: null,
    updated_at: null,
    manager: null,
    authManager: null,
    group_id: null,
    group_group_name: null,
    messages: [],
    utm: null,
    msg: null,
  },
  createGroup: {
    group_id: 0,
    group_group_name: '',
  },
  allGroup: [],
  addGroup: {
    id: null,
    group_id: null,
    group_group_name: null,
  },
  isAddGroupState: false,
  isDefaultGroupState: true,
  openedMessageOrderId: null,
  isCreateGroup: false,
  isDuplicate: false,
  isGroupOrder: null,
  isNoGroup: false,
  isUpdateEditOrder: null
};